### ISSUE TITLE
Error when running order elevation

### ISSUE THREAD

**Issue by hanzhao2020** [dalcinl/igakit#1]
A minimum working example for order elevation:
```
import numpy as np
from igakit.nurbs import *
k = np.array([[0,0,0,0.5,1,1,1]])
C = NURBS(k)
C.elevate(0,1)
```
Will get the following error:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    C.elevate(0,2)
  File "/home/usr/.local/lib/python3.8/site-packages/igakit/nurbs.py", line 1152, in elevate
    V, Qw = DegreeElevate(p, U, Pw, t)
igalib.error: (n>=1) failed for hidden n: DegreeElevate:n=-1
```

**Comment by dalcinl** [comment]
I cannot reproduce the the issue on my side. I'm using Python 3.10.2 and NumPy 1.21.5 from Fedora 35 system packages.

```
In [1]: import numpy as np
   ...: from igakit.nurbs import *
   ...: k = np.array([[0,0,0,0.5,1,1,1]])
   ...: C = NURBS(k)
   ...: C.elevate(0,1)
Out[1]: <igakit.nurbs.NURBS at 0x7ff624c8b5e0>

In [2]: C.degree
Out[2]: (3,)
```

Also note that your example uses `C.elevate(0,1)`, however your error message says `C.elevate(0,2)`. So there is a mismatch in your example code and your output. I cannot really guess what you are doing, so please provide a proper, isolated, minimal reproducer that triggers the issue independently of other code around.

**Comment by hanzhao2020** [comment]
Thanks for the verification, My Python version is 3.8.10 and NumPy is 1.22.3 from Ubuntu 20.04.4. Sorry for the mismatch in the error message. I tried elevation orders 1, 2, and 3, which all produce this error. The igakit is installed using the quick installation from GitHub. But I didn't see this error when the igakit was installed from BitBucket before. Thanks again.

**Comment by dalcinl** [comment]
OK, Now I can reproduce the problem. Looks like it is a regression from NumPy 1.22, and I do not know what's going on yet. In the mean time, If you install NumPy 1.21 it should work fine.

**Comment by hanzhao2020** [comment]
Yes, it works now, thank you.

**Comment by dalcinl** [comment]
Let's keep this issue open. I need to figure out what's going on, and eventually report the issue upstream to NumPy devs. I'm short of time right now, though.
